repos:
  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        files: ^backend/
        args: [--line-length=88]

  # Python linting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        files: ^backend/
        args: [--fix]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first

  # Frontend linting (optional - can be added later)
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.57.0
  #   hooks:
  #     - id: eslint
  #       files: ^frontend/src/.*\.(ts|tsx|js|jsx)$
  #       additional_dependencies:
  #         - eslint@8.57.0
  #         - typescript@5.3.3
